wandb_version: 1

_metadata:
  desc: null
  value:
    ref_type: typing.Any
    object_type: builtins.dict
    optional: true
    key: null
    flags: {}
    flags_root: false
    resolver_cache: {}
    key_type: typing.Any
    element_type: typing.Any
_parent:
  desc: null
  value: null
_flags_cache:
  desc: null
  value: null
_content:
  desc: null
  value:
    method: bayes
    program: src/group_99/train.py
    entity: s224225-danmarks-tekniske-universitet-dtu
    name: sweep
    project: mlopsproject_99
    metric: '{''goal'': ''minimize'', ''name'': ''validation_loss''}'
    parameters: '{''lr'': {''min'': 0.0001, ''max'': 0.1, ''distribution'': ''log_uniform_values''},
      ''batch_size'': {''values'': [32, 64, 128]}, ''epochs'': {''values'': [5, 10,
      15]}}'
    run_cap: '10'
    seed: '69420'
    num_classes: '23'
_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.19.1
    framework: huggingface
    huggingface_version: 4.47.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737539631
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 103
      - 105
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.12.7
      5: 0.19.1
      6: 4.47.1
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.00040511833551992054
