_content:
    value:
        entity: s224225-danmarks-tekniske-universitet-dtu
        method: bayes
        metric: '{''goal'': ''minimize'', ''name'': ''validation_loss''}'
        name: sweep
        num_classes: "23"
        parameters: '{''lr'': {''min'': 0.0001, ''max'': 0.1, ''distribution'': ''log_uniform_values''}, ''batch_size'': {''values'': [32, 64, 128]}, ''epochs'': {''values'': [5, 10, 15]}}'
        program: src/group_99/train.py
        project: mlopsproject_99
        run_cap: "10"
        seed: "69420"
_flags_cache:
    value: null
_metadata:
    value:
        element_type: typing.Any
        flags_root: false
        key: null
        key_type: typing.Any
        object_type: builtins.dict
        optional: true
        ref_type: typing.Any
_parent:
    value: null
_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
