hyperparameters:
  batch_size: 128
  lr: 0.01
  epochs: 5
  seed: 694290
  num_classes: 23
  dropout_rate: 0.5

sweep:
  program: train.py
  name: "sweep"
  project: "group99"  # change this
  entity: "s224225-danmarks-tekniske-universitet-dtu"