wandb:
  entity: "s224225-danmarks-tekniske-universitet-dtu"
  project: group_99
  name: run_${now:%Y-%m-%d_%H-%M-%S}

hyperparameters:
  batch_size: 64
  lr: 0.001
  epochs: 75
  seed: 694290
  num_classes: 23
  dropout_rate: 0.5
