method: bayes

program: train.py
name: "sweep"
project: "group99"  # change this
entity: "s224225-danmarks-tekniske-universitet-dtu" # change this
metric:
    goal: minimize
    name: validation_loss
parameters:
    learning_rate:
        min: 0.0001
        max: 0.1
        distribution: log_uniform_values
    batch_size:
        values: [32, 64, 128]
    epochs:
        values: [5, 10, 15]
run_cap: 10