name: Build & Push Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GROUP_99 }}
          service_account_key: ${{ secrets.GCPSA_KEY }}
          export_default_credentials: true

      - name: Configure docker to use gcloud
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t europe-west2-docker.pkg.dev/${{ secrets.GROUP_99 }}/mlops-99-docker/my-image:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GROUP_99 }}/mlops-99-docker/my-image:${{ github.sha }}
