wandb_version: 1

method:
  desc: null
  value: bayes
program:
  desc: null
  value: src/group_99/train.py
entity:
  desc: null
  value: s224225-danmarks-tekniske-universitet-dtu
name:
  desc: null
  value: sweep
project:
  desc: null
  value: mlopsproject_99
metric:
  desc: null
  value:
    goal: minimize
    name: validation_loss
parameters:
  desc: null
  value:
    lr:
      min: 0.0001
      max: 0.1
      distribution: log_uniform_values
    batch_size:
      values:
      - 32
      - 64
      - 128
    epochs:
      values:
      - 5
      - 10
      - 15
run_cap:
  desc: null
  value: 10
seed:
  desc: null
  value: 69420
num_classes:
  desc: null
  value: 23
_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.19.1
    framework: huggingface
    huggingface_version: 4.47.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737540391
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 103
      - 105
      3:
      - 14
      - 16
      - 23
      - 24
      - 37
      4: 3.12.7
      5: 0.19.1
      6: 4.47.1
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.005672933015990649
