_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
entity:
    value: s224225-danmarks-tekniske-universitet-dtu
method:
    value: bayes
metric:
    value:
        goal: minimize
        name: validation_loss
name:
    value: sweep
num_classes:
    value: 23
parameters:
    value:
        batch_size:
            values:
                - 32
                - 64
                - 128
        epochs:
            values:
                - 5
                - 10
                - 15
        lr:
            distribution: log_uniform_values
            max: 0.1
            min: 0.0001
program:
    value: src/group_99/train.py
project:
    value: mlopsproject_99
run_cap:
    value: 10
seed:
    value: 69420
