wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.19.1
    framework: huggingface
    huggingface_version: 4.47.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737545460
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 103
      - 105
      3:
      - 14
      - 19
      - 23
      - 37
      4: 3.12.7
      5: 0.19.1
      6: 4.47.1
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0004227881659118242
seed:
  desc: null
  value: 69420
num_classes:
  desc: null
  value: 23
