version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # The root directory of your project
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
