name: Weekly Dependency Updates

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday (weekly schedule)

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update dependencies with Dependabot
        uses: dependabot/fetch-metadata@v2
        with:
          package-ecosystem: "pip"
          directory: "/"
          schedule-interval: "weekly"

      - name: Update GitHub Actions workflows
        uses: dependabot/fetch-metadata@v2
        with:
          package-ecosystem: "github-actions"
          schedule-interval: "weekly"
