name: Python package

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Set Dataset Path (optional, if needed)
        run: |
          echo "DATASET_PATH: ${HOME}/.cache/kagglehub/datasets/vencerlanz09/sea-animals-image-dataste" >> $GITHUB_ENV


      - name: Test with pytest
        run: |
          pytest -v
