_content:
    value:
        batch_size: "128"
        dropout_rate: "0.5"
        epochs: "5"
        lr: "0.01"
        num_classes: "23"
        seed: "694290"
_flags_cache:
    value:
        struct: true
_metadata:
    value:
        element_type: typing.Any
        flags_root: false
        key: hyperparameters
        key_type: typing.Any
        object_type: builtins.dict
        optional: true
        ref_type: typing.Any
_parent:
    value: '{''hyperparameters'': {''batch_size'': 128, ''lr'': 0.01, ''epochs'': 5, ''seed'': 694290, ''num_classes'': 23, ''dropout_rate'': 0.5}, ''sweep'': {''program'': ''train.py'', ''name'': ''sweep'', ''project'': ''mlopsproject_99'', ''entity'': ''s224225-danmarks-tekniske-universitet-dtu''}}'
_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 16
                - 23
                - 55
                - 66
            "4": 3.12.7
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
